#...............................................................................
#
#  This file is part of the Doxyrest toolkit.
#
#  Doxyrest is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/doxyrest/license.txt
#
#...............................................................................

branches:
    only:
        - master

image: Visual Studio 2015

# we are building source tarball on AppVeyor, so don't convert to CR-LF

init:
    - git config --global core.autocrlf false

clone_folder: c:\projects\doxyrest
clone_depth:  1

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc10
        - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc14

install:
    - git submodule update --init
    - call doxyrest\ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%
    - call doxyrest\ci\appveyor\install.bat

build_script:
    - set THIS_DIR=%CD%
    - set THIS_DIR_CMAKE=%THIS_DIR:\=/%

    - mkdir %DOWNLOAD_DIR%\expat\build
    - cd %DOWNLOAD_DIR%\expat\build
    - cmake .. %CMAKE_CONFIGURE_FLAGS% %EXPAT_CMAKE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%

    - cd %THIS_DIR%
    - echo set (EXPAT_INC_DIR %DOWNLOAD_DIR_CMAKE%/expat/lib) >> paths.cmake
    - echo set (EXPAT_LIB_DIR %DOWNLOAD_DIR_CMAKE%/expat/build/%CONFIGURATION%) >> paths.cmake

    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%
    - call ..\ci\appveyor\build-source-package.bat

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure

artifacts:
    -   path: $(DOXYREST_SOURCE_PACKAGE_FILE)
        name: doxyrest_source_package

deploy:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: jpZmZjs4rexF7ix1wvN56hvAac2tGVAffQGsygfqMfR34Ls1SkvC1DQaf4On7RTB

    artifact: doxyrest_source_package
    force_update: true

    on:
        appveyor_repo_tag: true
        toolchain: msvc10
        configuration: Release
